apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
  labels:
    app: analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
        - name: analytics
          image: 823809779962.dkr.ecr.us-east-1.amazonaws.com/coworking-checkin:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: analytics-config
            - secretRef:
                name: analytics-secret
          ports:
            - containerPort: 5000